"""token minter, the

Revision ID: 2d006b2cf180
Revises: c31100b54916
Create Date: 2021-12-20 11:47:13.492382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d006b2cf180'
down_revision = 'c31100b54916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', '_metadata', new_column_name='asset_metadata')
    op.add_column('token', sa.Column('nonce', sa.Integer(), nullable=True))
    op.execute('UPDATE token SET nonce = 0')
    op.alter_column('token', 'nonce', nullable=False)
    op.add_column('token_contract', sa.Column('minter_id', sa.Integer(), nullable=True))
    op.add_column('token_contract', sa.Column('base_uri', sa.String(), nullable=True))
    op.create_foreign_key(None, 'token_contract', 'account', ['minter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_contract', 'base_uri')
    op.drop_column('token_contract', 'minter_id')
    op.drop_column('token', 'nonce')
    op.alter_column('token', 'asset_metadata', new_column_name='_metadata')
    # ### end Alembic commands ###
