"""nullable token tx.

Revision ID: 4562f4f9291a
Revises: aa3215a30502
Create Date: 2021-12-22 22:26:56.263316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4562f4f9291a'
down_revision = 'aa3215a30502'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'latest_tx_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('token', 'latest_tx_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
