"""block counter

Revision ID: 8dd84a8605b4
Revises: 8efbe5637f96
Create Date: 2021-12-10 15:45:42.514415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dd84a8605b4'
down_revision = '8efbe5637f96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contract', sa.Column('block_counter', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('contract', 'block_counter')
    # ### end Alembic commands ###
