"""account, token and limit order

Revision ID: 8efbe5637f96
Revises: c0920905c725
Create Date: 2021-12-10 00:47:57.515568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8efbe5637f96'
down_revision = 'c0920905c725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stark_key', sa.Numeric(precision=80), nullable=False),
    sa.Column('ethereum_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_contract',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('fungible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contract_id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Numeric(precision=80), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('latest_tx_id', sa.Integer(), nullable=False),
    sa.Column('ask_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['token_contract.id'], ),
    sa.ForeignKeyConstraint(['latest_tx_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('limit_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Numeric(precision=80), nullable=False),
    sa.Column('tx_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('bid', sa.Boolean(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=False),
    sa.Column('quote_contract_id', sa.Integer(), nullable=False),
    sa.Column('quote_amount', sa.Numeric(precision=80), nullable=False),
    sa.Column('closed_tx_id', sa.Integer(), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['closed_tx_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['quote_contract_id'], ['token_contract.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['tx_id'], ['transaction.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id')
    )
    op.create_foreign_key(None, 'token', 'limit_order', ['ask_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('token_ask_id_fkey', 'token', type_='foreignkey')
    op.drop_table('limit_order')
    op.drop_table('token')
    op.drop_table('token_contract')
    op.drop_table('account')
    # ### end Alembic commands ###
