"""unique account address.

Revision ID: aa3215a30502
Revises: e90d2a40cde8
Create Date: 2021-12-22 21:16:22.659074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3215a30502'
down_revision = 'e90d2a40cde8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['address'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('account_address_key', 'account', type_='unique')
    # ### end Alembic commands ###
