"""token metadata, or so

Revision ID: c31100b54916
Revises: 8dd84a8605b4
Create Date: 2021-12-20 00:43:29.402785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c31100b54916'
down_revision = '8dd84a8605b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('contract', 'stark_contract')
    op.alter_column('account', 'ethereum_address', new_column_name='address')
    op.add_column('token', sa.Column('name', sa.String(), nullable=True))
    op.add_column('token', sa.Column('description', sa.String(), nullable=True))
    op.add_column('token', sa.Column('image', sa.String(), nullable=True))
    op.add_column('token', sa.Column('token_uri', sa.String(), nullable=True))
    op.add_column('token', sa.Column('_metadata', sa.JSON(), nullable=True))
    op.add_column('token_contract', sa.Column('name', sa.String(), nullable=True))
    op.add_column('token_contract', sa.Column('symbol', sa.String(), nullable=True))
    op.add_column('token_contract', sa.Column('decimals', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token_contract', 'decimals')
    op.drop_column('token_contract', 'symbol')
    op.drop_column('token_contract', 'name')
    op.drop_column('token', '_metadata')
    op.drop_column('token', 'token_uri')
    op.drop_column('token', 'image')
    op.drop_column('token', 'description')
    op.drop_column('token', 'name')
    op.alter_column('account', 'address', new_column_name='ethereum_address')
    op.rename_table('stark_contract', 'contract')
    # ### end Alembic commands ###
